### ISSUE TITLE
Hooks to track element visibility

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/o-tracking#105]
Should track the _visibility_ of any element on the page.

```
<div data-o-tracking-element-visible>
 ...
</div>
```

Will count the number of seconds the element is, say, 50% visible in the viewport, or in cases where the element bounding rectangle is greater than the screen height the time it has remained in the viewport.

```
<div data-o-tracking-element-seen>
 ...
</div>
```

Similarly, a hook that fires once, when the top-left corner of the bounding box has passed, say, 30% in to the viewport.

Could be added to adverts, blocks of content, other components (eg, o-comments).

**Comment by JakeChampion** [comment]
This was added in o-tracking v1.5.0 but we forgot to close this issue, here is the PR which added the support -- https://github.com/Financial-Times/o-tracking/pull/199
