### ISSUE TITLE
Remove all cookie dependencies

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/o-tracking#11]
Apart from `FTSession`

**Comment by markstephens** [comment]
@commuterjoy with this ticket, do you mean o-tracking's dependencies on ft.com's cookies? Or the cookies o-tracking may set itself?

Or both? :)

**Comment by commuterjoy** [comment]
All cookies apart from FTSession and the one o-tracking needs to set an anon cookie.

**Comment by markstephens** [comment]
Ok, sweet.

**Comment by commuterjoy** [comment]
@markstephens hi - what did we agree here? Is this still setting a spoor-id cookie? I thought we'd agreed to move the to the server.

https://github.com/Financial-Times/o-tracking/blob/master/src/javascript/core/user.js#L40

**Comment by markstephens** [comment]
As discussed, put this cookie on .ft.com as a subdomain can't set a cookie on another subdomain.
