### ISSUE TITLE
Consider reducing cookie payload

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/o-tracking#111]
Next have started logging cookies sizes hitting their servers.

This first graph shows the _mean_ size in bytes per cookie (yellow is o-tracking) in our sample ...

![www hostedgraphite-23](https://cloud.githubusercontent.com/assets/84996/12722336/5d2e3ba0-c8fc-11e5-85da-af394fc5a8c2.png)

The second graph shows _max_ size (brown is o-tracking) and it shows some cookies are 4-5kb, which is probably over our [domain limits in some browsers](http://browsercookielimits.squawky.net/).

![www hostedgraphite-22](https://cloud.githubusercontent.com/assets/84996/12722304/33756e78-c8fc-11e5-86a6-b0ae5bfb5387.png)

**Comment by markstephens** [comment]
These will be browsers without localstorage enabled - and with dodgy connections.

o-tracking only forces an ID into a cookie, the rest it defaults to localStorage, but does fallback to cookies when it can't do localstorage.

**Comment by commuterjoy** [comment]
yup, but 5kb of cookies is not healthy, so can we fallback to something else?

**Comment by markstephens** [comment]
what else is there?

**Comment by commuterjoy** [comment]
what would be the consequence of not saving the state in this way?

**Comment by markstephens** [comment]
it's saving the events that don't make it to spoor-api, to retry again later

**Comment by commuterjoy** [comment]
mmm, i wonder if cookies aren't really designed for this sort of thing. i.e. it should only retry for localStorage enabled devices.

**Comment by AlbertoElias** [comment]
I agree with Matt, localstorage has  more than good enough support for this. Connection lost normally happens on mobile devices that have good enough browsers anyway

**Comment by markstephens** [comment]
Have you got a chart on how many people have a large o-tracking cookie? (As apposed to just the max size)

**Comment by commuterjoy** [comment]
![www hostedgraphite-40](https://cloud.githubusercontent.com/assets/84996/13149140/3b9946ba-d658-11e5-86c5-60f3f304ed0b.png)

a few hundred every hour (blue). the 5k max line (red) is probably a load of people hitting their cookie limit.

**Comment by markstephens** [comment]
That `max` is the max cookie size again, not people.

So, thats a count of requests with that cookie. How many of them were with a cookie more than 1k?
After-all, the mean cookie size is 1-1.5k.

**Comment by commuterjoy** [comment]
No idea, the data doesn't show it. I'll have to add extra logging.

**Comment by markstephens** [comment]
Ok, not trying to be a stick in the mud, I agree with you on the technical front. Just wanna know how it will affect things.

I guess couple of 100 per hour is not much...

**Comment by JakeChampion** [comment]
I'm looking into this now, unfortunately it has been a very long time since this issue was open and the grafana charts no longer work, which means we don't know if this is still a potential issue to fix -- https://grafana.ft.com/d/iCp3gVcWz/next-preflight-cookie-size?orgId=1

**Comment by JakeChampion** [comment]
With the help of @robsquires we have found the correct graphite data for recording cookie sizes.
Looking at [this graph](https://graphitev2-api.ft.com/?width=586&showTarget=next.heroku.router.web_1_process_cluster_worker_1_EU.headers.size.common.cookie.max&showTarget=next.heroku.router.web_1_process_cluster_worker_1_EU.headers.size.common.cookie.mean&height=308&target=next.heroku.router.web_1_process_cluster_worker_1_EU.headers.size.common.cookie.95th&target=next.heroku.router.web_1_process_cluster_worker_1_EU.headers.size.common.cookie.99th&target=next.heroku.router.web_1_process_cluster_worker_1_EU.headers.size.common.cookie.max&target=next.heroku.router.web_1_process_cluster_worker_1_EU.headers.size.common.cookie.mean) I believe that 5% of ft.com users have a cookie above 2kb and 1% have a cookie above 3kb.

<img width="630" alt="image" src="https://user-images.githubusercontent.com/1569131/88947275-3bddd380-d288-11ea-868e-7ea1ff5cc74b.png">

**Comment by commuterjoy** [comment]
enjoying this thread - happy memories.

**Comment by JakeChampion** [comment]
> enjoying this thread - happy memories.
👋 


We currently have no way to find out what the cookies are which make up the large size, I've asked Customer Products if this is on the roadmap. Without that information we are only guessing that o-tracking is the issue.

**Comment by JakeChampion** [comment]
Rob Squires found the code to track individual cookie sizes is still present behind an old flag named `preflightCookieTracking`. I'm speaking with Customer Products Platform team to reactivate the flag and get up-to-date data on what cookies are very large. If they are o-tracking cookies then we can look into fixing this. -- https://financialtimes.slack.com/archives/C3TJ6KXEU/p1596128045007700

**Comment by JakeChampion** [comment]
The flag has been reactivated but currently is not turned on for any users so we have no data yet -- https://financialtimes.slack.com/archives/C3TJ6KXEU/p1597933253000800?thread_ts=1596128045.007700&cid=C3TJ6KXEU

**Comment by JakeChampion** [comment]
When the flag eventually does get turned on for some of our users, the metric to search for in graphite is `next.heroku.preflight.*.cookies.large.*` (https://github.com/Financial-Times/next-preflight/blob/468de5b978a1b87c6f7ae5d10c8037fee74840c1/server/middleware/cookie-tracking.js#L35)

**Comment by JakeChampion** [comment]
Jira ticket to turn on the flag for all users -- https://financialtimes.atlassian.net/browse/CPP-258

**Comment by JakeChampion** [comment]
Flag has been turned on and it is true that o-tracking has the largest cookies of anything on ft.com @commuterjoy!!

The graphite query `highestMax(next.heroku.preflight.*.cookies.large.*.max, 10)` returned `o-tracking_clicks` cookie for every preflight worker.

If we run the query on only one worker we can see the top largest cookies `highestMax(next.heroku.preflight.web_1_process_cluster_worker_10_EU.cookies.large.*.max, 10)`
1. o-tracking_clicks
1. o-tracking_requests
1. DAPROPS
1. mp_412f41b9a2f5b1a17e172e08ee7b3691_mixpanel
1. _pdfps
1. liveagent_oref
1. xbc
1. ft_access_c
1. AppUser
1. FTConsent

**Comment by commuterjoy** [comment]
well, I had my suspicions 4 years ago :)

**Comment by JakeChampion** [comment]
I was hoping the 4 years would have somehow changed the results.

The new version of o-tracking will not be using a cookie based queue system so this will be resolved when that is released.

**Comment by commuterjoy** [comment]
thanks!

**Comment by JakeChampion** [comment]
For posterity -- here is the grafana dashboard we have to track cookies and their sizes -- https://grafana.ft.com/d/iCp3gVcWz/next-preflight-cookie-size?orgId=1&from=1599051413226&to=1599058671000

**Comment by JakeChampion** [comment]
This is fixed via https://github.com/Financial-Times/o-tracking/pull/293
