### ISSUE TITLE
Recommend source name for non cut the mustard fallback

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-tracking#114]
Currently next uses non-ctm, ft.com uses o-tracking-ns

I personally favour something like `o-tracking-core-fallback`, `o-tracking--core` or `o-tracking-core-experience`

**Comment by JakeChampion** [comment]
I can't find any `source` values which use a different name for the o-tracking fallback used in core (non cut the mustard) browsers.

Here are all the values we had in July:
1. o-tracking
2. ft-app-ios
3. amp-analytics
4. myft-digest
5. spoor-calibration
6. page-kit
7. next-service-worker
8. concurrency
9. sso-spoor-client
10. ft-app
11. webapp-ssr
12. envoy
13. ft-next-syndication-api
14. non-ctm
15. internal-products
16. next-webhooks

You can get the numbers for all those values in this Slack message -- https://financialtimes.slack.com/archives/CSW6B2VAN/p1596107554002200

**Comment by JakeChampion** [comment]
After [speaking with Chris Brown](https://financialtimes.slack.com/archives/C1WF81SR3/p1596133176228400?thread_ts=1596108623.219600&cid=C1WF81SR3) and the Data Platform team, they have never been asked to distinguish core users from enhanced users which shows this isn't something that is required or likely to be used.

We will update the examples we have in the readme to mention using a different `source` for core and enhanced could be useful for distinguishing between those users.

**Comment by wheresrhys** [comment]
It's a useful thing to know for calibrating how many pages are tracking all interactions and how many are not. e.g. if you expect X% of users to click on a new banner to call it successful, but 2% of users are in core experience &mdash; or maybe more temporarily due to some bug &mdash; then it's valuable to be able to discount those page views from the analysis.  

Not being asked to doesn't necessarily mean it has no value, just that the value has not been documented or communicated well.

Just adding as a footnote, and I think your solution is adequate from a 'what needs to be done in this library' standpoint 

:+1:

**Comment by chrisbrownuk** [comment]
@wheresrhys Yes, absolutely.  I can see that there is a value from a developer and testing point of view.  I was just saying that this isn't needed for business reporting that customer analytics performs.

**Comment by JakeChampion** [comment]
Fixed via https://github.com/Financial-Times/o-tracking/pull/290
