### ISSUE TITLE
A way to flag elements as trackable

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/o-tracking#12]
Next want a way to flag DOM paths the user is interacting with.

From the [next-beacon-component README](https://github.com/Financial-Times/next-beacon-component).

```
<div data-trackable="menu" data-trackable-terminate>
    <ul>
        <li data-trackable="item 1">
            <button data-trackable="hello">click me</button>
        <li data-trackable="item 2" data-trackable-once>
            ...
        <li>
            <span data-trackable="goodbye"></span>
    </ul>
</div>
```

The attribute data-trackable-terminate can be used to stop the tracking code collecting trackable attributes beyond a given node.

The attribute data-trackable-meta, containing a JSON string, can be used to send additional information in the event detail - properties of the JSON will be added as properties of the event detail

If the attribute aria-pressed exists on the target an additional property domPressed will be set to true.

The attribute data-trackable-once can be used to remove the tracking code after the first interaction with it. This is useful when you want to capture a user's interaction with something but not the fact they are repeatedly clicking something - Eg, opening a closing a menu.

Code -> https://github.com/Financial-Times/next-beacon-component/blob/master/src/utils/getDomPath.js

**Comment by JakeChampion** [comment]
o-tracking supports data-trackable now -- https://github.com/Financial-Times/o-tracking/blob/e2d9b150bbcbe6cdaf39c627791cb85409613dc2/README.md#parameters
