### ISSUE TITLE
unique ID per page view

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-tracking#121]
So it's possible to track how many times an action occurs per page view

Happy to implement this if it seems like a good idea @markstephens

**Comment by markstephens** [comment]
We already have it

**Comment by wheresrhys** [comment]
really!? I don't see it documented anywhere.

**Comment by wheresrhys** [comment]
Is it `request_id`? Bit misleadingly named. And it can be overridden per request so isn't tied to being a one-to-one mapping to page views. An addition of something with an appropriate name and immutable  would be appropriate I think

**Comment by markstephens** [comment]
Lucky it isn't request ID then!

It's sent as `context.root_id`
