### ISSUE TITLE
More control over url and referer

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-tracking#122]
For next error pages which (for rubbish technical reasons) are served from within iframes I'm doing some hackery to pass in the real url and referrer via a query string

```
     const query = qs.decode(window.location.search.substr(1));
            if (query.isInIframe) {
                context.referrer = query.originalReferer;
                context.url = query.originalUrl;
            }
```

This is passed in to `oTracking.init()`. 
For the page:view event it is completely ignored https://github.com/Financial-Times/o-tracking/blob/master/src/javascript/events/page-view.js#L18 
For custom events (via Core.track()) these bits of config are respected https://github.com/Financial-Times/o-tracking/blob/master/src/javascript/core.js#L88

I feel like 
a) url & referer should be added to context for every event
b) they should respect whatever is passed in to init

@markstephens @georgecrawford

**Comment by markstephens** [comment]
hang on a minute......

Why can't you pass url into `page()`? e.g.
```js
otracking.page({
    url: 'blah'
});
```
...and referrer can be passed here too

These are properties of the event, so wouldn't be set at init.

o-tracking does respect what is passed in at init, but it will reset properties which are at event level, so they're not accidentally repeated - by design.

**Comment by wheresrhys** [comment]
Why shouldn't page respect the context passed in to init but all custom events do?

**Comment by markstephens** [comment]
Are you asking if custom events do respect init's context, or saying they do.

I would image page and events work the same...?

**Comment by wheresrhys** [comment]
custom events do respect it, but page doesn't. So I propose fixing that

**Comment by markstephens** [comment]
but they are respecting it because you're hooking into `core.track` directly?

Or are you using otracking.event()?

**Comment by wheresrhys** [comment]
event, which calls core.track internally

**Comment by markstephens** [comment]
they both go through `core.track`

I'm only eyeballing the code, but it looks like both would keep the context from init.

Ah, I see it now...

The difference with `page` will be the default settings which attempt to fill in url and referrer for you.
https://github.com/Financial-Times/o-tracking/blob/master/src/javascript/events/page-view.js#L18-L21

I think that's what you're seeing, they're the only values that are overwritten by page and happen to be the ones you're trying to set on init.

I set context.product on init on ft.com and it's maintained for every event, so I think it just happens to be those values....

**Comment by wheresrhys** [comment]
To clarify, I think the behaviour for *all* events should be

 - begin context object with `root_id` etc.. all the system bits and pieces, including url and referrer
 - extend and override with all the properties passed in to `init()`
 - add any default properties for that type of event and any 'event specific' properties e.g. timestamp
 - add/override with properties set when initiating the specific event

Does that sound good?

As an addition (more relevant for @georgecrawford than next)

 - the set of context properties that were passed in to `init()` can be overridden at any time using a `setGlobalContext()` method or similar

**Comment by markstephens** [comment]
That's what it does already... no?

I still say it's not quote right that you want to set url on init. It's a property of an event, the page view event.
It's actually built that way for webapp and single page apps - where they would init only once for the entire session and then call page repeatedly.
Your solution of setting url value as a default before init is starting to infer that o-tracking will always be put on a normal website, with normal page loads, which won't be the case.

setGlobalContext function idea is ok.

**Comment by wheresrhys** [comment]
It also adds context to all other event types e.g. which page a click happened on. Without url being available on every event most of our tracking would be useless. Admittedly most of the time we don't need to set it manually as (I think) spoor just picks it up from headers, but for our error page use case, and all web app's, it's important to be able to set it globally

The way you suggest doing it would mean if e.g. the web app sends a page view event, a scroll depth event, an ad view event etc.... it would need to manage the url and pass it in to each of those events. I feel like o tracking should provide a mechanism to record when the url changes and then take care of adding this property to all events

I agree that oTracking shouldn't set url and referrer in context by default. Will tweak my suggestion to reflect

**Comment by markstephens** [comment]
This is why we have root_id, to be able to join the events together and lookup the url.
One aim was to keep the events smaller by not repeating info.
Repeating the info does make querying easier I guess.

**Comment by wheresrhys** [comment]
yes, much easier
