### ISSUE TITLE
"If certain properties are present in the payload they will enriched by Spoor and appended to the payload"

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/o-tracking#123]
![image](https://cloud.githubusercontent.com/assets/224547/13989552/d2f34f4a-f108-11e5-9641-a908910a7f21.png)

I'm a little confused by this line on https://github.com/Financial-Times/o-tracking/blob/master/docs/event.md. 

Should it instead read thus? 

> If certain properties are **not** present in the payload they will **be appended via Spoor enrichment.**

**Comment by JakeChampion** [comment]
Fixed by https://github.com/Financial-Times/o-tracking/pull/300
