### ISSUE TITLE
Queued events sent with incorrect url and referrer

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-tracking#125]
We think we've found a serious-ish bug. If a custom event is triggered on a page, but fails to get sent before the page unloads it will be left in the queue. The event won't have been decorated with url and referrer yet, so eventually when it is picked off the queue and sent it will have url and referrer for the incorrect page (as it will pick them up from the new page)

cc @ifyio @markstephens

**Comment by markstephens** [comment]
It will still be attached to the correct page view though, through o-tracking's internal mechanisms.

**Comment by wheresrhys** [comment]
Doesn't seem to be. We've seen events come through which only get sent from the next sign up form, but are sending the url as something else https://beacon.ft.com/chart/custom-query?query=signup%3Abounce-%3Ecount()-%3Egroup(page.location.pathname)-%3Eprint(Table)

**Comment by georgecrawford** [comment]
Mark means that the event record will be attached to the correct page record in Redshift. I don't think you're looking at that data in Beacon. You're talking about the URL associated with the event, which I don't think the data/analytics team really look at. Am I right, @markstephens ?

**Comment by markstephens** [comment]
Yes, that's what I meant.

**Comment by wheresrhys** [comment]
Oh OK. All the same data should be sending the correct url and referrer, otherwise the notion of spoor as a pipeline that can reliably be subscribed to is broken. e.g. this bug will affect Lantern as well won't it?

**Comment by markstephens** [comment]
- You shouldn't need to send url and referrer with each event, as they're all joined to the page.
- I don't think Lantern will be affected, like us, they don't even know there is a url on each event.
- Still, I'm surprised they get overwritten on the following page. Once the event has been crafted inside o-tracking and in the queue, it shouldn't be modified. And I can't think why it would be.

**Comment by wheresrhys** [comment]
> as they're all joined to the page

Via which mechanism? 

> like us, they don't even know there is a url on each event.

I thought the idea was that events going through spoor can be consumed as independent entities. Surely *the* place to go for the url of the page an event happened on is the event itself, not some extrinsic knowledge of how events tie together

> Once the event has been crafted inside o-tracking and in the queue, it shouldn't be modified.

That's precisely what is happening

**Comment by georgecrawford** [comment]
@markstephens I've always been confused by this. Because Spoor has a firehose, I assumed that all events should be richly decorated with metadata like URL, referrer, user info, etc., and not to rely on the page::event (parent::child) data model for that information. It'd be really good to discuss then clarify which attributes are not appropriate for events, and belong only on pages.

**Comment by georgecrawford** [comment]
I agree with Rhys, that there are plenty of consumers who need rich events and who can't benefit from the structured data that Redshift produces.

**Comment by markstephens** [comment]
I don't see the bug, looks ok to me.
https://youtu.be/r3q-Na89AkU

**Comment by georgecrawford** [comment]
Looks fine. What a thrilling video ;)

**Comment by wheresrhys** [comment]
a) It's intermittent
b) It was originally discovered by events that are only fired on the next subscription form appearing with a different page url
c) the code bears out that this could happen
