### ISSUE TITLE
Rename this component to o-spoor-client

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-tracking#127]
Because that's what it's become, and it becomes clearer to users that it's a part of the spoor pipeline rather than a generic tracking component @alicebartlett @markstephens

**Comment by markstephens** [comment]
I don't understand why this is necessary?

I would say o-tracking and spoor aren't coupled at all, and potentially either one could be swapped out and the other would still be relevant.

I'm just saying I need more reasoning..

**Comment by wheresrhys** [comment]
> o-tracking and spoor aren't coupled at all

o-tracking sends a property called spoor-id. Soon hopefully we will have more clarity on the spoor data model, and if o-tracking isn't set altered to support that data model by default I'd be very surprised. I'd also be very surprised if o-tracking gets used - even occasionally - to send data into any other system.

I know it's not wholly necessary to rename, but I think it would help comprehension of the spoor pipeline.  {name}-api partnered by {name}-client is a very clear naming convention, establishing where something is sending data to. I also don't see it as being an imminent concern, but at the point where our data models have reached agreement on their structure I personally think it's make sense to announce that as 'spoor v2', and it's be nice if we had an `o-spoor-client v2` to accompany it

**Comment by triblondon** [comment]
Origami has always adopted a policy of naming things after what they do.
We've resisted being clever or funny, and instead opted for clarity. Naming
things using arbitrary names creates an "in-joke" that only makes sense if
you are an insider. In that sense these arbitrary names are exclusionary
while origami tries to be as inclusive as possible.

o-tracking has the benefit of being related to the purpose of the module.
Spoor client requires you to know what spoor is and what it does. New hires
and external origami users will not.

**Comment by wheresrhys** [comment]
> Spoor client requires you to know what spoor is and what it does

I suppose my point is that using o-tracking already presupposes you have some understanding of what spoor is and does. And the flip side to the non-semantic naming is that if you do know that spoor is the FT tracking solution it's arguably easier to find o-spoor-client than to find o-tracking. And anyone who doesn't already know a little bit about spoor arguably has no place sending data into it as there are/will be standards about what data should be sent

**Comment by AlbertoElias** [comment]
I agree with Mark and Andrew, o-tracking is way clearer, and it could be the starting point for many to learn about spoor too. If someone needs to understand spoor to use o-tracking, then o-tracking should help explain it. But someone in the FT who wants to track their site using FT's conventional way should be able to just find this module and add it without worrying anymore, and I think that process would be harder if we renamed it. I'm going to close this issue, but if more people agree on the rename, feel free to reopen
