### ISSUE TITLE
Support spoor-test header

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/o-tracking#129]
https://spoor-docs.herokuapp.com/usage#test-data

**Comment by JakeChampion** [comment]
Not all the o-tracking data transport systems support custom headers.
`navigation.sendBeacon` does not allow custom headers to be set.
An image tag is another transport system and does not allow custom headers to be set.
The only transport system which supports custom headers is xhr.

**Comment by JakeChampion** [comment]
After speaking with the Data team (https://financialtimes.slack.com/archives/C1WF81SR3/p1595606856174300), we have decided to not use the spoor-test header and instead expose a configuration option in o-tracking called `test` which will change the `is_live` Spoor parameter to `false`. The `is_live` Spoor parameter is used to filter out test traffic from production traffic and is what we should have been using all along it seems :-)

https://github.com/Financial-Times/o-tracking/pull/288
