### ISSUE TITLE
Add some libraries to track common things

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/o-tracking#13]
For example,

- Scroll depth
- Viewability
- Click tracking
- Dwell

**Comment by markstephens** [comment]
When discussing with Andrew previously, we thought this should be a separate library.

Something like scrolling for example, there must be many things interested in scroll depth (ads, tracking, Next) so there should be a common library.

**Comment by markstephens** [comment]
Superseded by https://github.com/Financial-Times/o-tracking/issues/93
