### ISSUE TITLE
Behaviour of setting/getting root_id value is unclear

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/o-tracking#131]
Events a, b, c and d inherit p1 `root_id`, p2 does not.

If you remove line 2, event `a` generates an id and `p2` fails to inherit that too.

```
1. const oTracking = require('o-tracking');
2. oTracking.page({ p1: 1 });
3. CustomEvent('oTracking.event', {bubbles: true, cancelable: true, detail: { a: 1}});
4. CustomEvent('oTracking.event', {bubbles: true, cancelable: true, detail: { b: 1}});
5. CustomEvent('oTracking.event', {bubbles: true, cancelable: true, detail: { c: 1}});
6. CustomEvent('oTracking.event', {bubbles: true, cancelable: true, detail: { d: 1}});
7. oTracking.page({ p2: 2 });
```

/cc @chrisbrownuk 

Because of this I think,

https://github.com/Financial-Times/o-tracking/blob/5908d2ef33e791b12a99ec6900c872985b77d333/src/javascript/events/page-view.js#L40

Which means all events that are declare before the `page` call are unattributable to the visit.

**Comment by JakeChampion** [comment]
This was fixed in https://github.com/Financial-Times/o-tracking/pull/140 which was released in v2.0.10 :-D
