### ISSUE TITLE
On first initialisation, check for `spoor-id` in query param as well as cookie/LS

### ISSUE THREAD

**Issue by georgecrawford** [Financial-Times/o-tracking#143]
This helps devices with complicated journeys involving multiple, private cookie stores to join up their device ID to become a single visitor (see https://jira.ft.com/browse/DTPCA-48).

**Comment by JakeChampion** [comment]
After speaking to Chris Brown, we can see this is already solved in the data platform's post processing system.

Chris also recounted when they worked at another company who had implemented this exact feature (tracking id in query parameter being used).
>For example a car insurance site had this implemented but then copied a link with the parameter in and deployed it live with the link href containing the equivalent of spoor-id=undefined and then lots of their customers had their tracking cookie set to the literal undefined and all their visitors merged into one :scream:
>On reflection perhaps we should not add it to o-tracking but leave it to post-processing

We will not be adding this to o-tracking 👍
