### ISSUE TITLE
Capture all element attributes for click event

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/o-tracking#146]
At the moment, click event data only contains element attributes if they match `/^data-trackable|^data-o-|^aria-/`.

https://github.com/Financial-Times/o-tracking/blob/master/src/javascript/events/click.js#L70

Todo: Capture all attributes.

**Comment by JakeChampion** [comment]
Update link to new location in the codebase -- https://github.com/Financial-Times/o-tracking/blob/dff4f6fc7afcbbafe25590cb2e1b082369079179/src/libs/get-trace.js#L47

**Comment by JakeChampion** [comment]
@adambraimbridge Do you remember why we would want to capture all attributes? OR why we only capture these specific attributes?

**Comment by adambraimbridge** [comment]
Yes, it was a time when the new FT.com was still under development. 

> why [..] would [we] want to capture all attributes?

Although we knew we would want to know in future what things had been clicked on, we didn't know how detailed we wanted to be — or indeed what clickable things might yet be added. So the idea was to cast a wide net for six to twelve months and then reduce the noise to a sensible level. 

> why [do we only capture these specific attributes?

I believe it was originally set to only track clicks on elements with `data-trackable` attributes. This was under the assumption that we could/would add that attribute to 100% of elements that we wanted to track. 

Some elements which we _did_ want to track did not have `data-trackable` attributes, and it was not plausible/convenient to update the elements, so `^data-o-|^aria-` elements were included in the net. Personally, I'd have set it to track 100% of clicks — whether they're on clickable items or not — but I didn't have the seniority (read: confidence) to make that call at the time. 

As it turns out, we don't have a strong tradition of interrogating interactivity data — except on a superficial, counting-clicks model — so I think that at this point there's no requirement for tracking anything more than the minimum.

**Comment by JakeChampion** [comment]
Thanks for the excellent reply! 😄 

>As it turns out, we don't have a strong tradition of interrogating interactivity data — except on a superficial, counting-clicks model — so I think that at this point there's no requirement for tracking anything more than the minimum.

I think we can likely close this issue then without any further development work
