### ISSUE TITLE
Crumb trail

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-tracking#147]
Originally from @commuterjoy on n-instrumentation

There's a desire to see user journeys across Next.

At the start of a session we log the type of page the user has entered the site, say in local session storage.
And any subsequent page views we append the type of page to the same string.
We can use a simple key for this - E.g. F for Front-page, A for Article, S for Stream.
For example, FAFAFAFA would indicate someone who has entered at the front-page, visited an article then gone back to the front-page and picked another article and so on.

Or, FAAAAA would indicate someone who has come from the front-page who has then gone from article to article.

Just a theory at the moment. But I think this is simpler than trying to piece together millions of user journeys in the database.

**Comment by adambraimbridge** [comment]
This reminds me of, and fits nicely with, an idea I had about "usage behaviors", which are really just journeys ...
![image](https://cloud.githubusercontent.com/assets/224547/22560260/da003260-e96b-11e6-9c5a-4b583338141e.png)

**Comment by adambraimbridge** [comment]
... and for what it's worth, I thought this kind of thing through a bit here: https://docs.google.com/document/d/1gJq1eWZ1G6zfe9ATUU72jeRRTkOcANdEgVp9p-EPFRY/ 

Excerpt: 
Journey Map
Perhaps a Journey Map can be used to identify and catalogue every possible journey there is. Eg:
```
 • [Frontpage] 		-> [any article] -> [bounce]
 • [Frontpage] 		-> [any article] -> [sign in] 	-> [favourite] 	-> [bounce]
 • [Google search] 	-> [any article] -> [FT search] 	-> [bounce]
 • [Google AMP] 		-> [any article] -> [FT search] 	-> [any section] 	-> [any article] -> [bounce]
 • [Any social] 		-> [any article] -> [any barrier] 	-> [bounce]
 • [Specific FT campaign] 	-> [any article] -> [any barrier] 	-> [subscription conversion]
```

**Comment by JakeChampion** [comment]
@chrisbrownuk could I get your thoughts on this issue please?

Is it currently a hard problem to piece together user journeys? If it is, would this proposal help simplify that?
