### ISSUE TITLE
IE 11 Object doesn't support property or method 'findIndex'

### ISSUE THREAD

**Issue by tom-parker** [Financial-Times/o-tracking#149]
![image](https://cloud.githubusercontent.com/assets/900140/23071431/3aaa0db4-f526-11e6-85c9-975df8ab3559.png)

SCRIPT438: Object doesn't support property or method 'findIndex'
File: main.js, Line: 9080, Column: 3
Error is triggered when user perform any action on Alphaville, such as:
- sign in / out
- open menu

**Comment by JakeChampion** [comment]
`Array.prototype.findIndex` is not in IE11, nor is it in the [default polyfill.io bundle](https://polyfill.io/v2/docs/features/#Array_prototype_findIndex) of polyfills.
