### ISSUE TITLE
t is not a function. (In 't()', 't' is an instance of Event)

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/o-tracking#151]
This error is causing a lot of noise in Sentry. It looks to have persisted across several n-ui versions:

https://sentry.io/nextftcom/frontend/issues/220614387/
https://sentry.io/nextftcom/frontend/issues/222437568/
https://sentry.io/nextftcom/frontend/issues/219769960/
https://sentry.io/nextftcom/frontend/issues/218704873/
https://sentry.io/nextftcom/frontend/issues/222367508/

**Comment by JakeChampion** [comment]
We haven't heard anything since 2017 about this, I'm going to close the ticket. If the error is still happening let's reopen this.
