### ISSUE TITLE
Origami compliant initialisation

### ISSUE THREAD

**Issue by triblondon** [Financial-Times/o-tracking#16]
The module may initialise on any combination of:

* A call to `{export}.init()`
* When constructed as an instance eg `var foo = new {export}()`
* The `o.DOMContentLoaded` or `o.load` events

**Comment by AlbertoElias** [comment]
Would the use of a json script tag be useful here?

**Comment by triblondon** [comment]
Yes, it should probably support declarative config + init on domcontentloaded.

**Comment by markstephens** [comment]
This was fixed in https://github.com/Financial-Times/o-tracking/commit/d27ca80187c3f9d0e8bec0e7e9f15abccf3b80d7
