### ISSUE TITLE
Capture layout and orientation in the JSON model

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/o-tracking#17]
```
var getCurrentLayout = require('o-grid').getCurrentLayout;
var getOrientation = require('o-viewport').getOrientation;
```

/cc @markstephens

**Comment by AlbertoElias** [comment]
Should there maybe exist the possibility of products adding extra information?

**Comment by markstephens** [comment]
Yeah, I'm unsure about putting those inside oTracking as maybe there's a
product/device which doesn't have a layout/orientation. Maybe it's right,
need to think on it..

Extra info is also interesting. NGDA should track anything and everything,
but need to keep it structured so it's not out of control..



--
Mark Stephens
BI Solutions Architect
Financial Times Ltd ft.com
Email: mark.stephens@ft.com
Int Ext: 4251
Tel: 020 7873 4251

<https://www.facebook.com/financialtimes> <https://twitter.com/FT>
<http://www.linkedin.com/company/financial-times>
<https://plus.google.com/+FinancialTimes/posts>
<http://www.youtube.com/user/FinancialTimesVideos>

On 22 May 2015 at 15:44, Alberto Elias <notifications@github.com> wrote:

> Should there maybe exist the possibility of products adding extra
> information?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/o-tracking/issues/17#issuecomment-104678201>
> .
>

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by kaelig** [comment]
`getCurrentLayout` is definitely specific to products.

`getOrientation` could be bundled in oTracking? It is an interesting piece of information to have, and since that's 10 lines of code, I'm not sure there is a need to require o-viewport just for that.

**Comment by georgecrawford** [comment]
For info, the web app will also be sending `device.dimensions.width` and `device.dimensions.height` to represent the viewport, as we don't use origami components.

**Comment by commuterjoy** [comment]
FYI https://github.com/Financial-Times/o-tracking/pull/49

**Comment by georgecrawford** [comment]
Thanks. I’m currently reporting device.orientation (portrait|landscape), device.dimensions.width and device.dimensions.height, so this should match up. We don’t have an applicable concept of ‘layout’.




George

___________________

George Crawford
Senior Developer, Financial Times

+44 (0)752 567 9717
Number One Southwark Bridge,
London SE1 9HL



> On 29 Jul 2015, at 20:56, Matt Chadburn <notifications@github.com> wrote:
> 
> FYI #49
> 
> —
> Reply to this email directly or view it on GitHub.
> 


-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by commuterjoy** [comment]
@georgecrawford i noticed o-viewport also has [getSize](https://github.com/Financial-Times/o-viewport/blob/0ac4adbed32d0f9d87bfad882e454bdaafaa79e8/src/utils.js#L27) - perhaps we could add that to #49. Would that negate the need for device.dimensions.width and device.dimensions.height on the app?

**Comment by georgecrawford** [comment]
I'd prefer not to use that, as we try to avoid unnecessarily reading from the DOM, and already have in-memory caches of all the viewport measurements we might need. I haven't yet experimented with o-tracking in the app, but there are likely to be a few features like this which we'd ideally opt out of, passing in our own known values to work as efficiently as possible. 

If practical, I'd suggest that calls to o-tracking which contain viewport dimensions should not then make a call to o-viewport, whereas apps which don't pass values should by default benefit from o-viewport (or inlined equivalent, as @kaelig suggested).

**Comment by markstephens** [comment]
Wrote a response here:
https://github.com/Financial-Times/o-tracking/pull/49#issuecomment-126237674

**Comment by JakeChampion** [comment]
this was rejected as something to add to o-tracking -- https://github.com/Financial-Times/o-tracking/pull/49#issuecomment-126241300
