### ISSUE TITLE
Document data-trackable

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/o-tracking#176]
It's really useful but I figured out how to use it just by reading the code and searching other people's code on GitHub.

But there's absolutely no documentation that I could find anywhere.

This took ages.  A few notes would have saved me hours 😅 .

**Comment by matthew-andrews** [comment]
Something like this perhaps:-

#### Extra context

To add extra context to click events you may add `data-trackable-context-key="value"` where `key` is the field name of the extra context and value is the extra data.

For example:

```
<a href="https://www.ft.com/content/1234-1234-1234-1234"
	data-trackable="view-original-article"
	data-trackable-context-article_guid="1234-1234-1234-1234"
	data-trackable-context-article_source="FINANCIAL TIMES">
```

**Comment by JakeChampion** [comment]
Fixed via https://github.com/Financial-Times/o-tracking/pull/291
