### ISSUE TITLE
A polite request for better development tools

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/o-tracking#177]
I've been implementing o-tracking on my products lately and have struggled to check my events are correct.

I was wondering whether there was any appetite for a bit more investment into improving [Mollydobbin](https://github.com/Financial-Times/mollydobbin) or making something new to help developers check they've done the right things.

Things that are hard:-
- Because oTracking doesn't immediately send events, just looking at the networks tab can sometimes lead you into thinking it's not working, when it actually is.
- The networks tab is quite inconvenient to use because much of the data you want to check is buried quite deeply. (and a fair bit of noise is generated from the Options requests)

What I might like such a tool to do:-
- Show the stream of events with their associated properties, as they would get sent to spoor (ideally, in the case of click events, the domPath attributes string).
- Highlight areas of the page that should have `data-trackable` set but don't (as per mollydobbin).
- Tips on best practise naming of events / clicks / page views.

**Comment by JakeChampion** [comment]
> Things that are hard:-
> 
>     * Because oTracking doesn't immediately send events, just looking at the networks tab can sometimes lead you into thinking it's not working, when it actually is.
> 
>     * The networks tab is quite inconvenient to use because much of the data you want to check is buried quite deeply. (and a fair bit of noise is generated from the Options requests)

o-tracking has a developer mode, were you aware of the developer mode and if so, did you find it useful? The developer mode will not make any networks requests to Spoor but would instead log the event to the console immediately. I believe the developer mode was built to solve the two issues in the "Things that are hard" list you mentioned.


>     * Tips on best practise naming of events / clicks / page views.

We have a section in the readme which is aimed at helping come up with good names, I'll post it in a quote, could you let me know if it is helpful or of any improvements you would make to it?

>__Important__: To decide how to name the category and action fields, consider this sentence (square brackets denote that part is optional):
>
>#### A user can `{action}` a `{category}` `[` with/having a `{context}` `[` to `{destination}` `]` `]`
>
>For example:
>- A user can view a page having a uuid.
>- A user can play a video having a video ID.
>- A user can share a comment having a comment ID to Facebook.
>- A user can share an article having a uuid to email.
>- A user can scroll a page with a asset type.
>- A user can open an email.
>- A user can click an element.
>
>```js
>{
>    category: 'video',
>    action: 'play',
>    ... any other key-values ...
>    id: '512346789',
>    pos: '10'
>}
>```



> Highlight areas of the page that should have `data-trackable` set but don't (as per mollydobbin).

Do you mean make o-tracking behave exactly like mollydobin behaves? If so, I think we might be able to copy the mollydobin code into o-tracking and turn it on when o-tracking's developer mode is activated. What do you think?
