### ISSUE TITLE
What's the decision on browsers that don't pass CTM

### ISSUE THREAD

**Issue by AlbertoElias** [Financial-Times/o-tracking#18]
I've been reading a lot of discussions about this from a year ago. Was there a resolution? Does NGDA change it?

cc @triblondon @markstephens

**Comment by triblondon** [comment]
The standard invocation of NGDA ought to include an image fallback.  So the standard use case is:

* Page level declarative config
* A tag with `o--if-no-js` class containing a sub element with a tracker as a CSS background (see [spec for more details](http://origami.ft.com/docs/syntax/html/#anticipating-lack-of-script))

I would suggest something like:

```html
<div class='o-tracking o--if-no-js'><div style='background:url(...)'></div></div>
```

This is the CTM eqiv of `<noscript>`.

**Comment by markstephens** [comment]
I think we discussed it a lot a year ago because of NGDA. I also recall Andrew's suggestion above as what we would go with..

**Comment by AlbertoElias** [comment]
Yup, sounds good, I'll leave the issue open until it's properly documented

**Comment by markstephens** [comment]
It's in the readme: https://github.com/Financial-Times/o-tracking/blob/master/README.md#requirement-polyfills--doesnt-cut-the-mustard
