### ISSUE TITLE
Revert IE11 connection debugging

### ISSUE THREAD

**Issue by rowanbeentje** [Financial-Times/o-tracking#187]
https://github.com/Financial-Times/o-tracking/pull/186/files added some logic to send page view requests in IE11 a second time via the image subtype, to try and work out whether XMLHttpRequest issues are what's causing a failure in tracking in some circumstances.

This change needs to be reverted once we have a bit of data as to whether that caused the issue.

**Comment by JakeChampion** [comment]
This will be fixed in v3 of o-tracking, the pull-request has already been merged :-) https://github.com/Financial-Times/o-tracking/pull/280
