### ISSUE TITLE
Remove the version number from code

### ISSUE THREAD

**Issue by notlee** [Financial-Times/o-tracking#195]
The components version is specified in [`main.js` and `package.json`](https://github.com/Financial-Times/o-tracking/pull/194) and should be removed. 

Although it specifies `bower.json`, I also think it's fair to say it contradicts the [Origami specification](https://origami.ft.com/docs/component-spec/modules/).
>Must not include a version property. The version property is not needed and risks being out of sync with the repo tag

If there's a usecase for getting the version number from component JS, perhaps there's a way we can automate it across all our components.

**Comment by JakeChampion** [comment]
o-ads uses genversion and release-it scripts to automate adding a version property -- https://github.com/Financial-Times/o-ads/pull/192/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R20
