### ISSUE TITLE
pkg.browser field is incorrect or entrypoint file is not being included in bundle

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/o-tracking#208]
This is a bug with the npm version of this package.

## What

This package is missing a `main` field in its manifest or has an incorrect `browser` field which is preventing it being imported using a bare specifier.

## Details

Expected:

```js
import * as tracking from '@financial-times/o-tracking'
```

Reality:

```js
import * as tracking from '@financial-times/o-tracking/dist/javascript/core'
```

**Comment by JakeChampion** [comment]
The package.json has a browser field which points to browser.js, which does seem to exist.
You can see it working if you visit https://unpkg.com/@financial-times/o-tracking, it should redirect you to https://unpkg.com/@financial-times/o-tracking@1.7.2/browser.js

**Comment by JakeChampion** [comment]
I can confirm that the browser field points to a correct file.
Here is what I did:
```bash
➜  npm i @financial-times/o-tracking                                           
+ @financial-times/o-tracking@1.7.2
updated 1 package and audited 3 packages in 0.568s
found 0 vulnerabilities
➜  cat node_modules/@financial-times/o-tracking/package.json | grep '"browser"'
  "browser": "browser.js",
➜  wc node_modules/@financial-times/o-tracking/browser.js                     
     291     884    7488 node_modules/@financial-times/o-tracking/browser.js
```

**Comment by JakeChampion** [comment]
You can view the npm version of the package contents here: https://unpkg.com/browse/@financial-times/o-tracking@1.7.2/

**Comment by i-like-robots** [comment]
So my confusion here was caused by my tests written with Jest attempting to load the underlying module - but Jest uses the Node module resolution algorithm which doesn't know about the `browser` field.

Sorry. I've just come back from holiday.
