### ISSUE TITLE
Remove the version number from `main.js`

### ISSUE THREAD

**Issue by notlee** [Financial-Times/o-tracking#223]
The version of o-tracking is sent with each Spoor request.
As the version is set manually in `main.js` it [tends to
get out of date](https://github.com/Financial-Times/o-tracking/pull/221).

Find out if the version is used and if not remove it.

**Comment by JakeChampion** [comment]
I spoke with the data team (https://financialtimes.slack.com/archives/C1WF81SR3/p1596034996208300) and we believe the version parameter is being used so we need to keep it.
