### ISSUE TITLE
Better autoInit() behaviour

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-tracking#253]
Most origami modules require pretty much zero setup beyond html attributes if using build service. This is 👌 

o-tracking is nowhere near as plug & play. It requires:
1. Manually calling `.init()`, which may be configured imperatively or by including a script tag which contains the config json in the page
2. Manually calling `.page()`, passing in the appropriate URL and other optional metadata

The documentation is fragmented and largely follows a 'show some examples' style, but these are a bit muddled and full of dead ends (e.g. the docs for what config to pass in are full of "..." as example values, with no explanatory text other than the names of the config properties (which are often misleading, e.g. it turns out a valid value for _server_ is "https://spoor-api.ft.com/px.gif"). It's not clear which properties are required. It's not clear what - if anything - is also sent along with the data manually configured).

I propose that stages 1. and 2. above happen automatically in response to o-autoinit events

For backwards compatibility it could be opt in via an attribute included in the config json, or it could be made the default and released as a major version

**Comment by JakeChampion** [comment]
We already call `.init()` automatically on o-autoinit events -- https://github.com/Financial-Times/o-tracking/blob/dff4f6fc7afcbbafe25590cb2e1b082369079179/main.js#L272-L279

I don't think we can automatically call `.page()` because it would send a generic page view asset_type in the event instead of a more specific asset_type such as "story", "blog", "front", "video", "login". I'll do some research to see if these other asset_types are used, if they are not used then we could possibly add `.page()` into the o-autoinit event listener.

**Comment by chrisbrownuk** [comment]
The different asset_type values are used by analytics.

**Comment by JakeChampion** [comment]
Thank you @chrisbrownuk 👍 How did you figure that out? I'd love to be able to figure stuff like this out myself :-)

**Comment by JakeChampion** [comment]
> For backwards compatibility it could be opt in via an attribute included in the config json, or it could be made the default and released as a major version

Based on Chris Brown's statement that analytics use the asset_type of the page, I don't think we can make it default behavior for `page()` to be called automatically.

We can definitely add an attribute to turn automatic `page()` tracking :-)

**Comment by chrisbrownuk** [comment]
> 
> 
> Thank you @chrisbrownuk 👍 How did you figure that out? I'd love to be able to figure stuff like this out myself :-)

@Jake -  In this case, I just know that the BI and Insights teams use the asset type.  But for other questions I usually look at the Spoor data that we collect in Redshift (you could use Chartio to access the copy of this in BigQuery or access BigQuery directly, if you don't have Redshift access).

**Comment by JakeChampion** [comment]
closing this as per the discussion above
