### ISSUE TITLE
Respect `Do Not Track` header

### ISSUE THREAD

**Issue by georgecrawford** [Financial-Times/o-tracking#31]
Cf: https://github.com/Financial-Times/next-beacon/pull/13

**Comment by commuterjoy** [comment]
+1

**Comment by markstephens** [comment]
Why would you want to do this? What's the reason?

**Comment by kaelig** [comment]
Respect privacy in user settings, which is a just cause :+1:

**Comment by georgecrawford** [comment]
Exactly. It's a preference, and the browser isn't obliged to respect it yet, but it's good net etiquette.

**Comment by markstephens** [comment]
If the user is registered or subscribed, there is a monetary loss if we don't track them - we actually lose money.
If they're anonymous, it's less of an issue but could likely affect our decisions on new products.

So, we could respect it on anonymous users, but we absolutely can't for the others.

Ideally I would like to keep the tracking event, but strip some information when we get a DNT for an anonymous user, such as their geolocation and IP.
But then we're putting more logic and complexity into the collection endpoint, which we don't want to do.

**Comment by commuterjoy** [comment]
![www hostedgraphite](https://cloud.githubusercontent.com/assets/84996/8038724/15f3f08c-0dfd-11e5-8b8e-dd3fcd660435.png)

Last week's worth of DNT vs. total requests. It's actually a surprisingly high number - somewhere around 10-15% perhaps? I've not done any analysis on who is sending that header.

**Comment by markstephens** [comment]
I'm surprised it's that high!

I want to implement it even less now!

**Comment by adgad** [comment]
I think IE10 still has it on by default (although that is due to change -
http://blogs.microsoft.com/on-the-issues/2015/04/03/an-update-on-microsofts-approach-to-do-not-track/
)

On 8 June 2015 at 16:47, Mark Stephens <notifications@github.com> wrote:

> I'm surprised it's that high!
>
> I want to implement it even less now!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/o-tracking/issues/31#issuecomment-110050119>
> .
>

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by triblondon** [comment]
DNT is basically useless, and it offers users no reassurance.  There are
very few sites that react to it, and those that do usually don't react in a
way that matches the user's expectations.

Wikipedia says (emphasis mine):

> The Do Not Track (DNT) header is the proposed HTTP header field DNT that
requests that a web application disable either its tracking or cross-site
user tracking (**the ambiguity remains unresolved**) of an individual user.
The Do Not Track header was originally proposed in 2009 by researchers
Christopher Soghoian, Sid Stamm, and Dan Kaminsky.[1] **Efforts to
standardize Do Not Track by the W3C have so far been unsuccessful**

I don't think supporting it offers anyone any value.  There are a couple of
very well argued posts proposing better alternatives but I can't find them
right now.

**Comment by georgecrawford** [comment]
Thanks - interesting stuff.

**Comment by commuterjoy** [comment]
> I don't think supporting it offers anyone any value. 

I'm going to remove this from beacon.
