### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by notlee** [Financial-Times/o-tracking#327]
For example ensure public apis are as expected:
https://github.com/Financial-Times/o-tracking/pull/326

**Comment by chee** [comment]
i've started looking at this, and there appear to be tests that cover this? and they were added in the linked PR @notlee ?

**Comment by chee** [comment]
the test coverage of o-tracking appears to be very high, and the api mentioned in this issue is now tested thanks to @notlee's PR

**Comment by notlee** [comment]
Those tests cover internals not the public api. I was thinking some basic checks that `oTracking.click.init`, and other public functions, actually exist
