### ISSUE TITLE
Set spoor id in a cookie rather than local storage

### ISSUE THREAD

**Issue by markstephens** [Financial-Times/o-tracking#43]
https://jira.ft.com/browse/NGDA-104

**Comment by georgecrawford** [comment]
:+1: LS is disabled in Private Browsing Mode on iOS.

**Comment by markstephens** [comment]
Ah, this is done! (https://github.com/Financial-Times/o-tracking/pull/44)

o-tracking would've fallen back to a cookie anyway if LS didn't work, but we've forced the spoor id in a cookie regardless.
