### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/o-tracking#46]
In the Origami registry it states that o-tracking is at version `1.0.1`, which the [latest git-tag](https://github.com/Financial-Times/o-tracking/releases/tag/1.0.1) also states. The version within the `origami.json` and `main.js` state version `1` and `1.0.0` respectively.

**Comment by matthew-andrews** [comment]
`origami.json` version isn't the version of the module, it's the version of origami… of which there is only one :smile:

**Comment by triblondon** [comment]
and main.js ideally shouldn't contain a version number.
