### ISSUE TITLE
Add a demo

### ISSUE THREAD

**Issue by triblondon** [Financial-Times/o-tracking#48]
Demos make it easy for developers to immediately understand how to use an Origami component.  By creating a demo, you make it trivial for someone to integrate your component into their website project.

**Comment by triblondon** [comment]
The demo ought to include the non-CTM tracker mentioned in https://github.com/Financial-Times/o-tracking/issues/18

**Comment by markstephens** [comment]
fixed by https://github.com/Financial-Times/o-tracking/pull/55
