### ISSUE TITLE
Support CORs (optionally)

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/o-tracking#5]
We've split the web app's backend from its front end and now serve them over different hostnames so that (during development) we don't have to run a (heavy) backend when making front end changes.

To support this we needed to add CORs support into the tracking library -> http://git.svc.ft.com/projects/TRACK/repos/legacy-tracking-client-js/pull-requests/4/overview

It would be nice if `o-tracking` optionally supported CORs, too.

**Comment by markstephens** [comment]
closing, otracking is supporting cors. As Luke suggested, the collection endpoint is somewhere else anyway.
