### ISSUE TITLE
Promise-based API

### ISSUE THREAD

**Issue by georgecrawford** [Financial-Times/o-tracking#51]
Could we consider a Promise-based API for `page` and `event` please? It should use an existing implementation if present, rather than bundling a new one.

**Comment by wheresrhys** [comment]
As we discussed recently, as o-tracking currently supports 3 kinds of transport (image, xhr with cors or sendBeacon) the thing returned from a call to o-tracking isn't really predictable enough for it to be useful to handle it, and arguably we shouldn't add any kind of API that encourages users to attach functionality to the success/failure of a tracking event... bit of a dark pattern if you ask me.

Are there any specific use cases you had in mind? Or happy to close this?

**Comment by georgecrawford** [comment]
Nope. Can't remember ever wanting this, let alone why I did.
