### ISSUE TITLE
Consider category to be optional

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/o-tracking#72]
We've found a few cases where category is not really relevant and would like to make it optional in the o-tracking library.

We've got some code instrumenting scroll-depth of a webpage, so our action is _scroll_ or _scrolldepth_, but what's the category in this case? We don't feel it adds value to have to make one up.

**Comment by JakeChampion** [comment]
Custom o-tracking events have a default `category` of 'event' and a default `action` of 'generic'.

I've made a pull-request which documents that they are optional -- https://github.com/Financial-Times/o-tracking/pull/301

**Comment by JakeChampion** [comment]
Fixed by https://github.com/Financial-Times/o-tracking/pull/301
