### ISSUE TITLE
IE8 issues with the use of delete keyword

### ISSUE THREAD

**Issue by Thurst-ft** [Financial-Times/o-tracking#74]
Would it be possible to get the settings.delete method changed to something like settings.deleteValue or settings.remove? 

As per this article on stackoverflow it's generally best avoided: http://stackoverflow.com/questions/18793529/is-it-safe-to-declare-a-delete-method-in-javascript 

I appreciate that we can use CTM to fall back to the core experience but this seens liek a fairly minor revision to o-tracking that will help Membership support sign-up tracking in legacy browsers.

**Comment by markstephens** [comment]
this is changed
