### ISSUE TITLE
Link tracking sometimes gets allocated to the wrong URL

### ISSUE THREAD

**Issue by adgad** [Financial-Times/o-tracking#82]
/cc @tom-parker @markstephens @andygnewman

A lot of next click tracking is allocated to pages where that element doesn't exist. 

It looks like this is because our link click tracks get stored in cached and then called in the next page view (to prevent browsers cancelling the request etc) - so the URL should be kept when the click is stored.

https://github.com/Financial-Times/o-tracking/blob/master/src/javascript/link.js#L164

**Comment by markstephens** [comment]
@tom-parker and I worked out it was in Spoor Enrichment: https://github.com/Financial-Times/spoor-enrichment/blob/master/server/transforms/url.js#L27

We don't think the enrichment is bad though, and best thing is to specifically identify the url in the link event in `context.url`

**Comment by adambraimbridge** [comment]
Just to clarify: Is it not a case of the click event going into a queue, then later when it's processed from the queue, the user is on a different page?

**Comment by markstephens** [comment]
Yes, that is happening, but it's supposed to happen within o-tracking, as a
crucial feature.
o-tracking uses all the values from the "source" page, even though the
event is fired on the "destination" page.

The enrichment falls back to spoor-api's referrer when a url isn't manually
set, which is a decent enough fallback, would work 80% of the time.

The answer is to set context.url in the click event and then we know for
sure the page url.


--
Mark Stephens
BI Solutions Architect
Financial Times Ltd ft.com
Email: mark.stephens@ft.com
Int Ext: 4251
Tel: 020 7873 4251

<https://www.facebook.com/financialtimes> <https://twitter.com/FT>
<http://www.linkedin.com/company/financial-times>
<https://plus.google.com/+FinancialTimes/posts>
<http://www.youtube.com/user/FinancialTimesVideos>

On 30 October 2015 at 17:28, Adam Braimbridge <notifications@github.com>
wrote:

> Just to clarify: Is it not a case of the click event going into a queue,
> then later when it's processed from the queue, the user is on a different
> page?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/o-tracking/issues/82#issuecomment-152594452>
> .
>

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.
