### ISSUE TITLE
Should implement sendBeacon

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/o-tracking#9]
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon

**Comment by phamann** [comment]
Bump :+1: 

This is a feature currently in [`next-beacon-component`](https://github.com/Financial-Times/next-beacon-component/blob/master/src/beacon.js#L37) and something we will lose when moving Next over to o-tracking :(

**Comment by commuterjoy** [comment]
https://twitter.com/igrigorik/status/641718610910650368

soon in IE

**Comment by markstephens** [comment]
Implemented in https://github.com/Financial-Times/o-tracking/pull/96
