### ISSUE TITLE
Block-scoped declarations not yet supported outside strict mode

### ISSUE THREAD

**Issue by Thurst-ft** [Financial-Times/o-tracking#90]
Hi,

The inclusion  o-tracking is throwing: Uncaught SyntaxError: Block-scoped declarations for our b2b-sign-up-app. 

We've using webpack and have tried the strict-loader to no avail. Use babel seems rather heavy handed just to resolve this particular issue. So wondering if you guys have any suggestions on how this could be resolved.

**Comment by adambraimbridge** [comment]
@JakeChampion helped me when I encountered the same thing (or something very similar). I the solution is to put "use strict" back, and ignore or block the ES linting warnings.

**Comment by markstephens** [comment]
@Thurst-ft @jamesnicholls 

Can you try o-tracking version 1.0.16-alpha.1 in your builds please?
(http://build.origami.ft.com/bundles/js?modules=o-tracking%401.0.16-alpha.1)

Does it fix your issue?

**Comment by markstephens** [comment]
This is fixed in 1.0.16
